spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opb
    username: root
    password: ENC(kxuopkq/KXMDoluTftzp1ny6+Zj1rbBtqz7cNChT/IWSDE4azki0g5ptBR6oyKIc)
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  jpa:
    show-sql: true
secret:
  key: ENC(S/i16lOGf4iJmnIITKONL/920hvO4MtnKXJlOmWQKHA3W2qmuwayuQ31iuCaiAy6SylWax8MzKZRWJKkWUtymQ==)
  iv: ENC(gZ1qhmopxdAqmC4wpNNnfeAFP/rP+rF7k3wG2APmdm+HNaUp13XtY2o06lOi47fJ8ZsQkA4Anr4GUw2wEQY+Pw==)
  jwt: ENC(0aFqmqsTMmBTxJyGagODqLkkxL4ENwcaVMJvOFOQRz0vAHII8FML81o0dwjQL9WqtmuURGZ8XwANcIo+mXxsGl9jSr4OPX6t6OW8QvCrf7OEvqtksW3Md0uMv31VW+Z0)
server:
  servlet:
    context-path: /api
mail:
  clientID: ENC(h2pUhif92L45VwWU81nKzx3tKkJiVifw3Ai64X3JMI0VgsW5U0c7lZ4oTuBit7X81+E0MV/9o/2LKtuYwMg171zV5u/1smdiZEMwzOJpmW4=)
  clientSC: ENC(1qlrBn68L+JR3Nu3kzAg9JPJO8Gkw8SWWd/Rfg2mj7zsNHgW8OvqkQnZZC7DMDkDIAa6fQf2r2EyKldqqfZUMrxJwX8ywDtWe9yUgy17n1I=)
  tenantID: ENC(xgboaLK7YmRMPem1AViED+4lYFqxqPFhmYVlrsQheywX4s/QAYJhMAU36jkVG3T9ELJZcb1fF19oYaNypblH+7cYdGPUvXWW+jhh43dhAaw=)
  token: ENC(/BnDBISSjmu+LFa/1NWGMnxb1k2Tm8/vADBxSHQ6vPI3+XARHC6IbKT4sRWniOD8IIYZC7Gba5fZdg34EyJXlyDbpkbUkdmtaSwjNtw5lnPOSX9FTxXjnmrk4hvOFqlh0tQm4J5W9RTmaK9bQaTysMiaC6kIY5Ap8HhtG/2jgeg=)
  scope: ENC(oqYZQgcBiANhvfwdx/XKh1BcU5mXqO8HLHu4qULCHADAONQFDN3lCYAkrB1J+wlAzotSPrtXeJ1PLYLPOuPsX8Uyb8VipvfIWlsiH9F/yBA=)
  sender: ENC(F9UvRXyh4k7OcvO3zqb7TEWJsRUEBs9kjMuj85W6k8tZg3S5GKlIFBCI+nIDcUeRQFx2gGiiStKBHabXe1PZ1w==)
  host: ENC(llTS2uAvZTEpCgGBmT8cBE08+5zhru7azQOn8TSJ3o5VS+SCbkxxoeSrtllz7XFLK091kp+13A3DnV2b4x3t/g==)
  url: ENC(sdDX3Tx6NuaAjs1viYLxSClpR1Qp/IVBdv/Pd0Vs2jH3MMavLlu1R2WymPTzh++zyPDcALRFvKAB+nFr1shVB58apHGmRMqCqvSKMtJmnT4Et6bNx0F+UYg5yoJSM2hm)
  webtoken: ENC(UcrxHHCJ65/L1+ttok4DGvqg1pnEmQu6chxrDorrZuoSqfCWlIonfjReJRiWaGJrY4c0Vsp55jh/pvAOKygdoQ==)