spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opb
    username: root
    password: ENC(gTAil750PQr0dVqVAIUU/+fdNm71sSi21zjjRCuRSBxCeHtVl/sACAOivnFlXsrO)
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  jpa:
    show-sql: true
secret:
  key: ENC(S/i16lOGf4iJmnIITKONL/920hvO4MtnKXJlOmWQKHA3W2qmuwayuQ31iuCaiAy6SylWax8MzKZRWJKkWUtymQ==)
  iv: ENC(gZ1qhmopxdAqmC4wpNNnfeAFP/rP+rF7k3wG2APmdm+HNaUp13XtY2o06lOi47fJ8ZsQkA4Anr4GUw2wEQY+Pw==)
  jwt: ENC(0aFqmqsTMmBTxJyGagODqLkkxL4ENwcaVMJvOFOQRz0vAHII8FML81o0dwjQL9WqtmuURGZ8XwANcIo+mXxsGl9jSr4OPX6t6OW8QvCrf7OEvqtksW3Md0uMv31VW+Z0)
server:
  servlet:
    context-path: /api
mail:
  sender: ENC(1swez/+hIyX4e4SLPY3Iu1t10FuZUmMsiCznMNaKFTn6yTA4ImJLlP7eQSVKyc7k5m4FHjsnNKjBovBOQMpg7w==)
  pwd: ENC(RmVpwubTelTD924qEPDrq2JbyJbOS0vPNTEG55tz/Gh7X9VfgM83Am0X0Pk6lJ82by3eOC9+pzN5gk3lzvCweg==)
  host: ENC(Rmw+fCPLdgctZ4dhGSrcgrb/pBImz/dYex3oICY+eP8pnwDIXT3zMzTN1JfWbx/3/WAZe2A0uRyclfJOr8hvyw==)
  recipient: ENC(qwBfM/wpqS2aDlqlyYCTp/XN16divdwbD306gOXU4bnhN4yUNrunHMBhENDH3uohn0al5qQcyx3HTzVyB6AR2w==)