spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opb
    username: root
    password: ENC(BWUcrByDAr3crs514QEiENCY1/HHG1k0xTZlCQRUykRBkO11w7USV1+vqPKiB2Tc)
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false